name: Simple Windows Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "README.md"

jobs:
  windows-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "windows-only"
